export const events_upcoming = [
  // {
  //   title: "High-Octane Tournament",
  //   description: `It's time to rev up your engines and showcase your engineering prowess like never before. 🏎️💨
  //   The Engineer Team is thrilled to announce the High-Octane Tournament with a mind-blowing prize pool of 30K ! 🚀
  //   Whether you're a mechanical genius, a tech wizard, or a design maverick, this tournament is made for YOU! 🛠️`,
  //   fee: "Registration fee: Rs1500/- per team",
  //   insta: `https://www.instagram.com/p/CxfL7tESOmh/?igshid=MzRlODBiNWFlZA==`,
  //   registration: `https://docs.google.com/forms/d/e/1FAIpQLSdRJ0dTt7UTVF_oqT_pbss-4PdtCUJ0bQYcFGQ7nhN1WxGXzg/viewform`,
  //   rule_book: `https://drive.google.com/file/d/15cIjsjS3yN-PAQ4S1IBXr5jvbbWbUPT8/view?usp=drivesdk`,
  //   src: "/images/Events/upcoming_events.jpeg",
  //   link: "future-tech-symposium",
  //   type: "external",
  // },
];

export const events_22 = [
  {
    src: "/images/Events/website.png",
    title: "Website Release",
    text: "Website of SAE NITK",
    desc: "SAE NITK launched its official website, showcasing its projects, events, and achievements.The revamp of the club website started in October 2020. A new website has been developed with the aim of making it more interactive for the users and simplifying the various procedures involved in the club. It has been built using React JS as compared to the current website that was built using WordPress. It is a responsive website that has various front end and back end features for presenting valuable club information such as projects, blogs, members, etc., to the outside world. A lot of dedicated effort from the web development team has gone into the development of this new website. Presently, it is under final stages of development and testing. The release is expected soon.",
    link: "website-release",
    type: "external",
    date: "March 15, 2022",
    platform: "Online",
    speakers: "SAE Web Team",
  },
  {
    src: "/images/Events/autocad.png",
    title: "AutoCAD KEP",
    text: "A user tour of AutoCAD",
    desc: "The KEP was conducted by Pradeep Singh Solanki, a third year mechanical engineering student part of SAE NITK. A brief introduction of the software was given. The use of AutoCAD in architecture, civil engineering, interior design, automobile industry, aerospace industry, mechanical engineering and fashion designing was explained by the speaker. This was followed by a user tour of AutoCAD. Toggle keys like ortho, snap, dynamic input, polar tracking, dynamic UCS, workspace switching, etc. were discussed. The use of templates and plotting was also covered. 2D modelling commands available in the draw panel and modify panel were explained. Dimensioning, introducing text elements, the use of layers, etc., were also discussed. An introduction to 3D modelling features such as extrude, sweep, revolve, etc was given. The attendees were able to understand various other aspects of the software such as visualization of spot, point, weblight, shadow effect of sun, location, material browser rendering, environment settings, etc.",
    link: "autocad_22",
    type: "external",
    date: "July 31, 2022",
    platform: "Microsoft Teams",
    speakers: "Pradeep Singh Solanki",
  },
  {
    src: "/images/Events/ansys.jpg",
    title: "Ansys KEP",
    text: "An intro to the Ansys Software",
    desc: "The KEP was conducted by Sumit Sagar, a third year mechanical engineering student part of SAE NITK. The KEP started with an introduction to ansys software. The different modules of the software such as static structural, thermal, fluent, Computational Fluid Dynamics (CFD), etc., were discussed. The attendees were given an overview of the prerequisite topics required to understand the analysis, such as the concepts of stress, strain, conservation laws, etc. A brief introduction to Finite Element Analysis (FEA) was given along with the details about the representation of Partial Differential Equations in the different modules. The concept of meshing was given separate focus. The speaker also emphasized on the correctness and validation of the results obtained. The demonstration of the different features of the software was done with the help of a real life problem statement. Analysis of a bicycle pedal crank was discussed in the KEP.",
    link: "ansys",
    type: "external",
    date: "August 01, 2022",
    platform: "Microsoft Teams",
    speakers: "Sumit Sagar",
  },
  {
    src: "/images/Events/fusion360.png",
    title: "Fusion 360 KEP",
    text: "An intro and demonstration of the Fusion 360 Software",
    desc: "The KEP was conducted by Shunu PS and Guhan Sidharth M, third year mechanical engineering students part of SAE NITK.It started with an introduction to the User Interface of the Fusion 360 software. Various 2D drafting and sketching features such as circles, rectangles, polygons, editing capabilities such as fillet, chamfer, and other options such as patterns, etc., were discussed. Different topics of 3D part modelling such as extrude, revolve, holes, shell, etc., were also covered. The attendees were given a question to solve and practice. An introduction to assembly modelling was given, which was followed by a detailed demo of modelling a universal joint assembly and a simple slider joint. The concept of Add-ins and scripts was covered. The modelling of a simple gear drive was done, which included the implementation of revolute joints and motion links. Various other aspects such as animate joint, animate model, interference detection, component color cycling toggle, introduction of McMaster Carr components, section analysis and joint limits were also touched upon",
    link: "fusion360",
    type: "external",
    date: "October 16, 2022",
    platform: "Microsoft Teams",
    speakers: "Shunu PS and Guhan Sidharth M",
  },
];

export const events_21 = [
  {
    src: "/images/Events/webinar-rspant.jpg",
    title: "Webinar By RS Pant",
    text: "Webinar focused on meditation and yoga which helps in handling anxiety.",
    desc: "The webinar was conducted by Dr. Rajkumar S Pant, a professor in the Department of Aerospace Engineering, Indian Institute of Technology, Bombay. It was focused on meditation and yoga which helps in handling anxiety especially in the pandemic scenario. It started off with a brief discussion about the COVID-19 pandemic scenario until then: its causes, its effects on public health, effects on other sectors with a special focus on the aerospace sector. 'Equip or Enrich yourself' – a formula to gear up and make oneself future-proof was discussed. A gist of how minds do actions and techniques to develop bare observations were covered. Finally, all the participants performed a form of Buddhist meditation 'Anapana Sati', which translates to 'mindfulness of breathing'. This 10-minute activity enabled the attendees to witness the real feeling of how effective meditation can produce a calm and relaxed mind.",
    link: "webinar-by-r-s-pant",
    type: "external",
    date: "April 10, 2021",
    platform: "Zoom Webinar",
    speakers: "Mr. RS Pant",
  },
  {
    src: "/images/Events/matlab.jpeg",
    title: "MATLAB KEP",
    text: "Focused on installation, different sources, coding, GUI and built-in apps of MATLAB.",
    desc: "The KEP was conducted by Diwakar S Goud. The first phase focused on installation of Matlab. The different sources to learn about the software were also explored. In the second phase, basic coding, the GUI, and the different built-in apps in Matlab were covered. The event was open to members of the club.",
    link: "matlab-kep",
    type: "internal",
    date: "October 23, 2021",
    platform: "Online Session",
    speakers: "N/A",
  },
  {
    src: "/images/Events/simulink.jpeg",
    title: "Simulink KEP",
    text: "Covered Simulink libraries, simulation techniques, and real-time applications.",
    desc: "The event was conducted by Rishu Kumar and Ankit Gupta in two phases. The first phase covered the basics of Simulink, including an overview of the software, types of models, toolboxes, and shortcuts. Mathematical toolboxes like sine, transfer functions, gain, and display were introduced, and a simple step function was simulated to demonstrate trigonometric functions. The second phase focused on advanced features, including PID controllers, tuning methods, transfer functions of first and second order, graph visualization, and optimization. The event was open to club members",
    link: "simulink-kep",
    type: "internal",
    date: "November 5, 2021",
    platform: "Online Session",
    speakers: "N/A",
  },
  {
    src: "/images/Events/solidworks.png",
    title: "SolidWorks KEP",
    text: "Introduction to 3D modeling and design principles using SolidWorks software.",
    desc: "The KEP was conducted by Eshwar Sai Srinivas, covering a wide range of SolidWorks topics from sketching to custom weldments. Basics of sketching, including drawing lines, circles, and applying constraints like tangent and horizontal, were discussed with examples. Sketch patterns and section planes were explained. 3D modeling concepts such as extrusion, loft, and sweep were covered, along with editing features like trim, fillet, and chamfer. Modelling problems involving orthographic-to-isometric view conversion, multi-section solids, helix springs, and weldments were also discussed. The event was open to club members.",
    link: "solidworks-kep",
    type: "internal",
    date: "November 15, 2021",
    platform: "Online Session",
    speakers: "N/A",
  },
  {
    src: "/images/Events/adobe.jpg",
    title: "Adobe Workshop",
    text: "Session on Adobe Photoshop and Illustrator for graphic design and editing.",
    desc: "The KEP was conducted by Islavath Manohar, focusing on photo editing tools in Adobe Photoshop. Topics included the use of layers and filters, essential shortcuts, and editing images captured with a camera. The event was open to club members.",
    link: "adobe-workshop",
    type: "external",
    date: "December 1, 2021",
    platform: "Online Workshop",
    speakers: "N/A",
  },
  {
    src: "/images/Events/cosmol.png",
    title: "COMSOL Workshop",
    text: "Introduction to COMSOL Multiphysics for simulation and modeling.",
    desc: "A 2 hour KEP on Comsol was conducted by Rajat Shukla, Convenor of SAE NITK. Basics of modelling and analysis were covered along with battery modelling, heat transfer and fluid flow analysis. The event was open to the members of SAE NITK and other students of NITK as well. ",
    link: "comsol-workshop",
    type: "internal",
    date: "December 10, 2021",
    platform: "Online Workshop",
    speakers: "N/A",
  },
  {
    src: "/images/Events/gate-webinar.jpg",
    title: "Internship Webinar",
    text: "Prepare for your interviews",
    desc: "The webinar was conducted in two phases. The first phase covered research and management internships, with Rajat Shukla discussing fellowships, applications, and core domain internships. Rishu Kumar and Ankit Gupta provided insights on cold mailing, while Sagar focused on the IAS fellowship, SOPs, and LORs. Shuvam Senapati, former SAE NITK convenor, spoke about CAT, careers, and management internships. The second phase focused on industrial internships, with Kaustubh Sonawane and Eshwar Sai Srinivas discussing core domain internships from campus, Nisarg Shah and Karan Jain covering non-core domains, and Pradeep Kumar Modi sharing insights on off-campus core internships at IOCL, SAIL, GARC, etc. The event was open to all NITK students, and speakers actively addressed participants' questions.",
    link: "internship-webinar",
    type: "external",
    date: "March 13, 2021 (Phase 1) & March 14, 2021 (Phase 2)",
    platform: "MS Teams",
    speakers:
      "Rajat Shukla, Rishu Kumar, Ankit Gupta, Sagar, Shuvam Senapati, Kaustubh Sonawane, Eshwar Sai Srinivas and Pradeep Kumar Modi",
  },
  {
    src: "/images/Events/gate-webinar.jpg",
    title: "GATE Webinar",
    text: "Guidance session on preparing for the GATE examination.",
    desc: "The event aimed to help undergraduate students learn from GATE toppers about conceptual understanding, preparation strategies, time management, and mock test approaches. It also covered GATE's role in securing PSU/government jobs, research positions at DRDO, BARC, etc., and higher studies opportunities in IITs, IISc, and foreign universities like NUS and NTU. Hosted by Diksha Negi and Pradeep Singh Solanki, the speakers included Abhisheka Shetty (AIR 05, GATE 2021 ME, sponsored by Exergic) and Bharath Desikan (AIR 17, GATE 2021 CE, NITK alumnus). Students from NIT Surathkal, MNNIT Allahabad, NIT Silchar, and other colleges participated.",
    link: "gate-webinar",
    type: "external",
    date: "December 20, 2021",
    platform: "Online Session",
    speakers: "N/A",
  },
  {
    src: "/images/Events/magazine.jpeg",
    title: "Magazine Release",
    text: "Release event of the annual technical magazine featuring research and projects.",
    desc: "The second volume of SAE NITK’s annual magazine, Techbuzz, was released this year with the theme of Electric Vehicles. It features 14 articles covering the historical, technical, financial, and environmental aspects of EVs, authored by members from various SIGs. 'Exergic' is the official sponsor for Techbuzz Vol 2. (List of articles available in Appendix – Page 33).",
    link: "magazine-release",
    type: "internal",
    date: "December 30, 2021",
    platform: "Online",
    speakers: "N/A",
  },
];

export const events_20 = [
  {
    src: "/images/Events/autocad.png",
    title: "AutoCAD Workshop",
    text: "Aimed at covering basics of AutoCad.",
    link: "autocad-workshop",
    type: "external",
    date: "August 7, 2019",
    platform: "In-person on the campus",
    speakers: "Mr. Sachin Kuchekar",
    desc: "The workshop aimed at covering the basics of 2D and 3D design and modeling of automobile components using the AutoCAD software. It was a hands-on session where the attendees had to follow the instructions given by the speaker, Mr. Sachin Kuchekar, third-year Mechanical Engineering, and implement them on their own system. The event spanned for around 2 hours, starting with the basics of the software such as 2D design using different tools followed by the 3D modeling of a crankshaft.",
  },
  {
    src: "/images/Events/mind-fiz.jpg",
    title: "The Mind Fiz",
    text: "Online event based on AutoCAD",
    link: "the-mind-fiz",
    type: "external",
    date: "September 28, 2019",
    platform: "In-person on the campus",
    speakers: "SAE NITK",
    desc: "It was a 24-hour online event, the problem statement for which was circulated to the registered Participation and they were required to submit their CAD files having the full assembly of a CV Axle. It was conducted after the AutoCAD Workshop conducted by SAE-NITK to help the attendees practice the knowledge gained in the workshop.",
  },
  {
    src: "/images/Events/kasting.jpg",
    title: "Kasting",
    text: "A presentation on crankshaft part of automobiles.",
    link: "kasting",
    type: "external",
    date: "October 18, 2019",
    platform: "In-person on the campus",
    speakers: "SAE NITK",
    desc: "SAE-NITK in collaboration with MetaMorph, Metallurgy Committee as part of our technical fest, Engineer’19, conducted a presentation on the crankshaft part of automobiles, in addition to the process of building a sand mold and the explanation of various tools used for it. Furthermore, the presentation was followed by a demonstration of the casting process of the crankshaft using Aluminium metal. The event was an hour-long including the presentation and the casting demo.",
  },
  {
    src: "/images/Events/matlab-simulink.jpg",
    title: "MATLAB & Simulink Workshop",
    text: "Focused on covering basics of MATLAB.",
    link: "matlab-and-simulink-workshop",
    type: "external",
    date: "October 23, 2019",
    platform: "In-person on the campus",
    speakers: "Mr. Pradeep Modi",
    desc: "The two-day workshop focused on MATLAB basics, covering scalar, vector, and matrix operations, strings, and plotting on day 1, followed by functions, cell arrays, and mathematical optimization using Gauss-Seidel and other methods on day 2. Conducted by Pradeep Modi, a third-year Mechanical Engineering student, it was a hands-on session where attendees executed instructions on their systems. Each session lasted 2-3 hours, including Q&A, and received highly positive feedback from the audience.",
  },
  {
    src: "/images/Events/otto-quiz.png",
    title: "Otto Quiz",
    text: "Competition based on automobiles for the first-year students",
    link: "otto-quiz",
    type: "external",
    date: "October 29, 2019",
    platform: "In-person on the campus",
    speakers: "Mr. Anish Dua and Mr. Diwakar Goud",
    desc: "Otto Quiz was an automobile-themed competition for first-year students, hosted by second-year Mechanical Engineering students Anish Dua and Diwakar Goud. It featured a single round of non-factual, engaging questions designed to create a fun and interactive atmosphere. The quiz lasted an hour, and while all participants performed well, only one emerged as the winner.",
  },
  {
    src: "/images/Events/keynote.jpg",
    title: "Keynote Talk Series",
    text: "Event conducted in collaboration with SAEINDIA",
    link: "keynote-talk-series",
    type: "external",
    date: "January 28-30, 2020",
    platform: "In-person on the campus",
    speakers:
      "Mr. Prakash Verma, Mr. Sreeram S., Ms. Devayani Kulkarni, Mr. Devaraj Tuppad, Mr. Neelakandan Chandrasekaran",
    desc: "The Keynote Talk series, held from January 28th to 30th in collaboration with SAEINDIA, featured distinguished speakers from the automotive industry. The inaugural ceremony, presided over by Dr. Jagannath Nayak (DSW) and Prof. Ananthanarayana V.S. (Deputy Director), was MCed by Shaurya Seth (SAE-NITK President) and included the launch of SAE magazine Techbuzz. Day 1 featured a 3-hour session on Autonomous Vehicles by Prakash Verma, Sreeram S., and Devayani Kulkarni from Robert Bosch Engineering. Day 2 covered Hybrid and Electric Vehicles in a session by Devaraj Tuppad from Vitesco Technologies. On the final day, Neelakandan Chandrasekaran from 3M India Ltd. delivered a talk on Smart Materials, followed by an engaging Q&A session. The event concluded with remarks from faculty advisor Prof. Poornesh Kumar and Shaurya Seth, ending with a group photo.",
  },
  {
    src: "/images/Events/Career-building.jpg",
    title: "Career Building KEP",
    text: "A knowledge exchange program",
    link: "career-building-kep",
    type: "internal",
    date: "March 12, 2020",
    platform: "In-person on the campus",
    speakers: "Mr. Rahul Madhograhia and Mr. Dhruv Thakkar",
    desc: "The Knowledge Exchange Program (KEP) featured insights from Rahul Madhograhia (Convenor, SAE-NITK 2019-20) and Dhruv Thakkar (Final-year, Mechanical Engineering). The session began with Rahul presenting CV/Resume building tips, an overview of letters of recommendation—what they are and how to obtain them—and details about internship opportunities in India and abroad. Attendees were also guided in drafting their CVs using LaTeX. The session concluded with Dhruv sharing his personal experiences, providing clarity on the processes and intricacies involved.",
  },
];
